### ISSUE TITLE
Calendar cells too tall on mobile

### ISSUE THREAD

**Issue by jillh510** [bengolden/community_calendar#9]
On a small width screen, the date boxes look strange.
![screen shot 2018-01-25 at 9 35 39 am](https://user-images.githubusercontent.com/2319837/35403011-240b3458-01b3-11e8-814a-b759f7dd4744.png)

**Comment by bengolden** [comment]
This is still not great, but a bit better:

<img width="287" alt="screen shot 2018-02-11 at 4 59 07 pm" src="https://user-images.githubusercontent.com/3323292/36079816-e7650950-0f4c-11e8-82a8-8d161b9047c9.png">
